version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./docker/conf.d:/etc/nginx/conf.d
    networks:
      - atlas_network

networks:
  atlas_network:
    driver: bridge
